import { Open_Sans as FontSans } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" className={`${fontSans.variable}`}>
      <body className="min-h-screen overflow-x-hidden overflow-y-scroll bg-neutral-900 text-neutral-200 antialiased">
        {children}
      </body>
    </html>
  );
}
